plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.devtools.ksp)
    alias(libs.plugins.dagger.hilt)
}

android {
    compileSdk = libs.versions.compileSdkVersion.get() as Integer
    buildToolsVersion = libs.versions.buildTools.get()

    defaultConfig {
        minSdk = libs.versions.minSdkVersion.get() as Integer
        targetSdk = libs.versions.targetSdkVersion.get() as Integer
    }
    compileOptions {
        sourceCompatibility = JavaLanguageVersion.of(17)
        targetCompatibility = JavaLanguageVersion.of(17)
    }
    buildTypes {
        release {
        }
    }
    lint {
        abortOnError = true
    }
    namespace = 'musicmate.mediaserver.jupnp'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

configurations {
    httpcoreOriginal
}

def patchHttpCore = tasks.register("patchHttpCore", Jar) {
    archiveFileName.set("httpcore5-android.jar")
    destinationDirectory.set(layout.buildDirectory.dir("patched-libs"))
    from(configurations.httpcoreOriginal.elements.map { files ->
        files.collect { zipTree(it.asFile) }
    }) {
        exclude "org/apache/hc/core5/util/ReflectionUtils.class"
        exclude "org/apache/hc/core5/reactor/SingleCoreIOReactor*.class"
    }
}

dependencies {
    httpcoreOriginal libs.apache.httpcore

    implementation project(':core')
    implementation project(':server-jupnp')
    implementation project(':library:library')

    implementation libs.androidx.annotation
    implementation libs.androidx.core

    implementation libs.jupnp.android
    implementation libs.jupnp.support
    api files(patchHttpCore)
    api(libs.apache.http2core) {
        exclude group: 'org.apache.httpcomponents.core5', module: 'httpcore5'
    }

    implementation libs.kotlin.coroutines.core
    implementation libs.dagger.hilt.android
    ksp libs.dagger.hilt.compiler

    testImplementation libs.junit
}